let nederlandsoriginal = [
    "Drink 3 slokken als je een meisje bent",
    "Drink 3 slokken als je een jongen bent",
    "${player1} moet een adje doen, het spijt me",
    "${player2} mag 8 slokken uitdelen",
    "${player1} mag een adje uitdelen",
    "${player2} en ${player1} doen steen papier schaar, je mag zelf kiezen hoeveel slokken je wilt",
    "Staarwedstrijd tussen ${player2} en ${player1}! Wie verliest drinkt 3 slokken",
    "Drink het aantal slokken dat gelijk is aan het aantal mensen met wie je zou slapen ${player1}",
    "${player1} geeft ${player2} een dare, als je het goed doet, drinkt de ander 5 slokken en andersom",
    "Als je kaas lekker vindt (ook gesmolten) mag je 3 slokken uitdelen",
    "Als je bananenijs lekker vindt moet je 5 slokken drinken om de bananensmaak weg te spoelen",
    "Als je een kroket lekker vindt mag je 3 slokken uitdelen",
    "De eerste persoon die met een dobbelsteen een 6 gooit mag 6 slokken uitdelen, als je geen dobbelsteen hebt moet degene die dit leest ze drinken",
    "Als je ooit een seksuele gedachte hebt gehad over iemand hier aanwezig moet je 3 slokken drinken",
    "De eerste die de grond aanraakt mag iedereen 1 slok geven",
    "Speel 'ik ga op reis en neem mee'. Wie als eerste afgaat drinkt 4 slokken",
    "Speel het wijs-spel. Als ${player1} kijkt naar de richting waarnaar ${player2} wijst, moet deze 5 slokken drinken en omgekeerd",
    "${player1}, hoeveel aanwezige mensen zou je zoenen? Drink dat aantal slokken",
    "${player1} moet een liedje neuriën, de eerste die het raadt deelt 5 slokken uit (niet aan de artiest)",
    "Als je volledig wit bent moet je 5 slokken drinken",
    "Als je niet wit bent mag je 5 slokken uitdelen",
    "De jongste persoon mag 3 slokken uitdelen omdat ze toch gepest worden",
    "De kleinste persoon mag 5 slokken uitdelen als deze de langste persoon een high-five kan geven",
    "Wijs met z'n allen naar 1 persoon, die moet 3 slokken drinken. Tel af van 3",
    "${player1}, vertel iets wat niemand van je weet. Als je niets zegt moet je een 5 slokken drinken",
    "Wat is de hoofdstad van Burkina Faso? Als je het raadt mag je 10 slokken uitdelen, anders drink je 3 slokken",
    "Als het langer dan week geleden is dat je seks hebt gehad moet je 3 slokken drinken, ik hoop dat het snel verandert 😔",
    "Als je ooit iemand van hetzelfde geslacht leuk hebt gevonden mag je 3 slokken uitdelen",
    "Hoi, ${player1}! Vertel je beste grap als niemand lacht moet je 3 slokken drinken, anders mag je er 5 uitdelen",
    "${player1}, raad de favoriete kleur van de personen naast je, voor elke goede kleur mag je 3 slokken uitdelen",
    "Bel een familielid en laat ze kiezen tussen kop of muntje, als ze kiezen voor kop mag je 3 slokken uitdelen, anders drink je 5 slokken",
    "Noem om de beurt andere woorden voor 'vagina'. De eerste die er geen meer weet moet 5 slokken drinken",
    "De persoon die het laatst naar het toilet is geweest moet 3 slokken drinken. Wat een zwakke move",
    "Drink 3 slokken als je drank van iemand anders drinkt, skere hond",
    "De eerste die een drankje adt, mag iemand anders laten adten",
    "TREK EEN BAK ${player1}",
    "Wie is het laatste aangekomen? Doe een adt",
    "${player1}, doe een kikker na of drink 5 slokken",
    "DOE EEN WATERVAL, eindig met ${player1}",
    "${player1}, drink 5 slokken, de persoon rechts van je 4, daar rechts van 3, ...",
    "${player1}, laat je laatste 3 foto's zien op je telefoon of drink 5 slokken",
    "Beslis met z'n allen wie de slimste persoon is, deze drinkt 3 slokken. Wijsneus",
    "Als je nagellak draagt mag je 2 slokken uitdelen",
    "${player1} en ${player2} zijn nu drinkbuddies! Als de een drinkt, drinkt de ander ook",
    "Speel never have I ever, de persoon die het eerst alle vingers kwijt is drinkt 3 slokken",
    "Bier- en wijndrinkers moeten 2 slokken drinken. Cocktailsuperioriteit!",
    "De eerste persoon die de wordle van vandaag oplost mag 5 slokken uitdelen",
    "Werkloze mensen mogen 3 slokken uitdelen",
    "Drink evenveel slokken als dagen die je niet gedoucht hebt",
    "${player1}, ga voor 3 rondes op de schoot van de persoon links van je zitten of drink 3 slokken",
    "${player1}, drink 3 slokken, je bent de gekozen avatar",
    "Doe een dansje ${player1} of drink 5 slokken",
    "${player1} mag een liedje uitkiezen, als de rest hem leuk vindt mag je 3 slokken uitdelen",
    "De persoon links van de gamemaster is de nieuwe gamemaster. De oude gamemaster mag 3 slokken uitdelen voor de service",
    "De volgende persoon die een drankje drinkt mag 3 slokken uitdelen",
    "De volgende persoon die zich verspreekt mag 3 slokken drinken",
    "${player1}, drink 3 slokken, je bent de nieuwe gamemaster",
    "${player1}, hou de hand vast van ${player2} tot het spel gedaan is. Drink beide 3 slokken als je de hand los laat",
    "Drink 3 slokken als je een iPhone hebt",
    "Als je een iPhone hebt mag je 2 slokken uitdelen",
    "De mensen die geen alcohol drinken mogen 3 slokken uitdelen",
    "Als je een slok drinkt mag je 2 slokken uitdelen",
    "${player1} heeft een anytimer op ${player2}",
    "Drink evenveel slokken als dat je dieren hebt",
    "Witte schoenen drinken 2 slokken per witte schoen",
    "Is je liefde als een waterval? Drink dan 3 slokken",
    "Singles mogen 3 slokken uitdelen",
    "Hoeveel is jouw outfit waard? Meer dan 200 euro? Schenk dan het glas van de persoon rechts van je in",
    "${player1}, je mag 3 slokken uitdelen als je een instrument speelt",
    "Drink als er ooit iemand op je is vreemdgegaan",
    "Als je schoenmaat kleiner is dan 40 moet je 2 slokken drinken",
    "Als je patat zegt in plaats van friet moet je 3 slokken drinken gozur",
    "${player1} stel een vraag aan ${player2}, als deze het beantwoordt moet je 5 slokken drinken, anders drinkt de ander 3 slokken",
    "Drink evenveel slokken als kleuren die je aanhebt",
    "Koffie of thee? De minderheid drinkt 2 slokken",
    "${player1}, wie ken jij het slechtst? Geef die persoon 3 slokken",
    "Als je pittig eten aankan mag je 3 slokken uitdelen",
    "Als je games speelt moet je 3 slokken drinken",
    "${player1}, schenk een glas in voor ${player2} en geef die persoon 3 slokken",
    "Als je graag koffie drinkt mag je 2 slokken uitdelen",
    "Blondjes moeten 2 slokken drinken",
    "${player1}, spel het woord 'jasmijnthee' omstebeurt met ${player2}. Wie het verpest drinkt 2 slokken anders delen jullie allebei 2 slokken uit",
    "Drink evenveel slokken als het aantal soorten drugs je ooit hebt gedaan",
    "Verzin met z'n allen een bijnaam voor ${player1}, tot het einde van het spel eet de persoon zo. Zeg je de echte naam, moet je 3 slokken drinken",
    "De gamemaster zegt Marco, de laatste die polo zegt moet 3 slokken drinken",
    "De laatste die z'n neus aanraakt moet 3 slokken drinken",
    "Kattenmensen mogen 1 slok uitdelen aan 1 hondenpersoon",
    "Armpjedrukken tussen ${player1} en ${player2}, de verliezer moet 2 slokken drinken voor de zwakte",
    "Rijmwoorden, verzin een rijmwoord. De eerste die niet rijmt of niets verzint drinkt. ${player1} begint.",
    "${player1}, speel fuck, marry, kill. Als je het niet wil doen drink je 2 slokken",
    "${player1} moet een slok drinken zonder handen, als je knoeit moet je 5 slokken drinken",
    "Als je je benen gekruist hebt moet je 2 slokken drinken",
    "Zeg omstebeurt een woord om samen een zin te vormen. De persoon die het verpest moet 3 slokken drinken",
    "${player1}, wat is je favoriete fruit? Dat is je bijnaam tot het einde van het spel",
    "${player1}, wat is de achternaam van Obama? Heb je het fout, moet je 3 slokken drinken. Shame on you",
    "Als je vandaag minder dan 2000 stappen hebt gezet moet je 2 slokken drinken, jij luie zak",
    "Wie is je favoriete persoon aanwezig? Geef deze persoon een knuffel en drink samen 3 slokken",
    "${player1}, schud iedereens handen. Voor elke persoon die je geen hand geeft drink je 1 slok",
    "Als je cigaretten rookt moet je 3 slokken drinken",
    "Als je vapet mag je 3 slokken uitdelen",
    "Als je 43 drinkt mag je iemand 3 slokken en een ander 4 slokken uitdelen",
    "Passoa of soortgelijke drankjesdrinkers moeten 3 slokken drinken",
    "${player1}, wat is je favoriete kleur? Je bijnaam is dan je favoriete kleur",
    "Is ${player1} groter dan ${player2}? Dan moet deze 3 slokken drinken",
    "Pasta of friet? De minderheid drinkt 2 slokken",
    "${player1} zeg je beste openingszin tegen ${player2}. De groep bepaalt of je 3 slokken mag uitdelen of niet",
    "Als je deze week gesport hebt moet je 2 slokken drinken. Je bent té goed bezig dus even compenseren",
    "Als je ooit vakken hebt gevuld moet je 3 slokken drinken",
    "Als je vegetarisch ben mag je 5 slokken uitdelen, go you",
    "De eerste persoon die iets bruins ziet mag 3 slokken uitdelen",
    "De laatste persoon die 2 handen in de lucht doet moet 3 slokken drinken",
    "Mensen zonder rijbewijs drinken 2 slokken",
    "De minst dronken persoon drinkt 3 slokken",
    "${player1}, doe 5 squats met een slok tussen elke squat",
    "De volgende persoon die op de telefoon kijkt (behalve de gamemaster) moet 5 slokken drinken",
    "De persoon die ooit heeft geplast op iemand anders mag 5 slokken uitdelen",
    "${player1}, wissel de drankjes van 2 spelers naar keuze",
    "${player1}, noem 3 liedjes van Avril Lavigne of drink 3 slokken",
    "${player1}, lik de voorarm van ${player2} of drink 3 slokken}",
    "${player1} en ${player2}, wissel van schoenen of drink 5 slokken",
    "Ben je of heb je het ooit iemand gedumpt via je telefoon? Deel dan 3 slokken uit",
    "${player1}, doe een filmscene na zonder geluid te maken. Jij en de persoon die het raadt mogen 3 slokken uitdelen. Anders drink je zelf 3 slokken",
    "De persoon die het laatst seks heeft mag 3 slokken uitdelen",
    "Als je een emo girl leuk vindt moet je 3 slokken drinken",
    "${player1} als je een handstand kan, laat het zien. Anders neem je 3 slokken",
    "Kies tegelijk tussen biefstuk met friet of boterkoek. Iedereen die het antwoord met de meeste stemmen hebben gekozen mogen 3 slokken uitdelen",
    "Avondmensen mogen 5 slokken uitdelen",
    "${player1} fluister een zin in het oor van de persoon rechts van je. Klopt de zin aan het einde van de ronde nog, hoeft niemand te drinken", 
    "Swifties, jullie mogen 3 slokken uitdelen",
    "Ring dragers mogen 3 slokken uitdelen",
    "Ga een rondje in de bus ${player1}",
    "Noem de titel van het liedje dat nu opstaat. Als er geen muziek is of je raadt het fout moet je 3 slokken drinken",
    "Als je alcohol hebt gedronken voordat het legaal was moet je 3 slokken drinken. Slecht van je",
    "Als je vandaag een kopje koffie hebt gedronken moet je 3 slokken drinken",
    "${player1} finish de tekst: '130 op de' of drink 3 slokken",
    "Als je uit een glas drinkt mag je 3 slokken uitdelen. Environmentalist",




];