let englishoriginal = [
    "Drink 3 sips if you're a girl",
    "Drink 3 sips if you're a boy",
    "${player1} has to do an ad, I'm sorry",
    "${player2} must take 8 sips",
    "${player1} must do an adje",
    "${player2} and ${player1} do rock paper scissors, you may choose how many sips you want",
    "Staring contest between ${player2} and ${player1}! Whoever loses drinks 3 sips",
    "Drink the number of sips equal to the number of people you would sleep with ${player1}",
    "${player1} gives ${player2} a dare, if you do well, the other person drinks 5 sips and vice versa",
    "If you like cheese (also melted) you may hand out 3 sips",
    "If you like banana ice cream you have to drink 5 sips to wash away the banana taste",
    "If you like a croquette you may hand out 3 sips",
    "The first person to roll a 6 with a die gets to hand out 6 sips, if you don't have a die the person reading this has to drink them",
    "If you have ever had a sexual thought about anyone here present you must drink 3 sips",
    "The first one to touch the ground gets to give everyone 1 sip",
    "Play 'I'm going on a trip and I'm taking with me'. Whoever goes down first drinks 4 sips",
    "Play the pointing game. If ${player1} looks at the direction to which ${player2} is pointing, they must drink 5 sips and vice versa",
    "${player1}, how many people present would you kiss? Drink that number of sips",
    "${player1} must hum a song, the first to guess it distributes 5 sips (not to the artist)",
    "If you are completely white you must drink 5 sips",
    "If you are not white you may hand out 5 sips",
    "The youngest person gets to pass out 3 sips because they get bullied anyway",
    "The smallest person gets to pass out 5 sips if they can high-five the tallest person",
    "All of us point to 1 person, they must drink 3 sips. Count down from 3",
    "${player1}, tell something no one knows about you. If you don't say anything you have to drink a 5 sip",
    "What is the capital of Burkina Faso? If you guess it you may hand out 10 sips, otherwise drink 3 sips",
    "If it has been more than week since you had sex you must drink 3 sips, I hope it changes soon 😔",
    "If you've ever liked someone of the same sex you may pass out 3 sips",
    "Hi, ${player1}! Tell your best joke, if no one laughs you must drink 3 sips, otherwise you may hand out 5",
    "${player1}, guess the favorite color of the persons next to you, for each correct color you may hand out 3 sips",
    "Call a family member and let them choose between heads or tails, if they choose heads you may hand out 3 sips, otherwise you drink 5 sips",
    "Take turns naming different words for 'vagina'. The first one who doesn't remember any must drink 5 sips",
    "The person who went to the toilet last has to drink 3 sips. What a weak move",
    "Drink 3 sips when you drink someone else's drink, poor dog",
    "The first one to adt a drink may let someone else adt",
    "DO A BAK ${player1}",
    "Who arrived last? Do an adt",
    "${player1}, act like a frog or drink 5 sips",
    "DO A WATERFALL, finish with ${player1}",
    "${player1}, drink 5 sips, the person to your right 4, over there to the right 3, ...",
    "${player1}, show your last 3 pictures on your phone or drink 5 sips",
    "Decide together who is the smartest person, this one drinks 3 sips. Wise person",
    "If you're wearing nail polish, you get to pass out 2 sips",
    "${player1} and ${player2} are now drinking buddies! If one drinks, the other drinks too",
    "Play Never Have I Ever, the person who puts all fingers down first drinks 3 sips",
    "Beer and wine drinkers must drink 2 sips. Cocktail superiority!",
    "The first person to solve today's wordle gets to hand out 5 sips",
    "Unemployed people may hand out 3 sips",
    "Drink as many sips as days you haven't showered",
    "${player1}, sit on the lap of the person to your left for 3 rounds or drink 3 sips",
    "${player1}, drink 3 sips, you are the chosen avatar",
    "Do a dance ${player1} or drink 5 sips",
    "${player1} may choose a song, if the others like it you may hand out 3 sips",
    "The person to the left of the gamemaster is the new gamemaster. The old gamemaster gets to hand out 3 sips for service",
    "The next person to take a drink may hand out 3 sips",
    "The next person to slip up may take 3 sips.",
    "${player1}, drink 3 sips, you are the new gamemaster",
    "${player1}, hold the hand of ${player2} until the game is done. Drink both 3 sips when you release the hand",
    "Drink 3 sips if you have an iPhone",
    "If you have an iPhone you may hand out 2 sips",
    "The people who don't drink alcohol may hand out 3 sips",
    "If you drink a sip you may pass out 2 sips",
    "${player1} has an anytimer on ${player2}",
    "Drink as many sips as you have animals",
    "White shoes drink 2 sips per white shoe",
    "Is your love like a waterfall? Then drink 3 sips",
    "Singles are allowed 3 sips",
    "How much is your outfit worth? More than 200 euros? Then pour the glass of the person to your right",
    "${player1}, you may give away 3 sips if you play an instrument",
    "Drink if anyone has ever cheated on you",
    "If your shoe size is less than 40 you must drink 2 sips",
    "If you say chips instead of French fries you must drink 3 sips",
    "${player1} ask a question to ${player2}, if they answer it you must drink 5 sips, otherwise you drink 3 sips",
    "Drink as many sips as colors you are wearing",
    "Coffee or tea? The minority drink 2 sips",
    "${player1}, who do you know the least? Give that person 3 sips",
    "If you can handle spicy food you may hand out 3 sips",
    "If you play games you must drink 3 sips",
    "${player1}, pour a glass for ${player2} and give that person 3 sips",
    "If you like to drink coffee you may hand out 2 sips",
    "Blondes should drink 2 sips",
    "${player1}, spell the word 'jasmine tea' in turns with ${player2}. Whoever messes up drinks 2 sips otherwise you both hand out 2 sips",
    "Drink as many sips as the number of types of drugs you have ever done",
    "All of you make up a nickname for ${player1}, until the end of the game the person is named like this. If you say the real name, you have to drink 3 sips",
    "The gamemaster says Marco, the last one to say polo has to drink 3 sips",
    "The last one to touch his nose has to drink 3 sips",
    "Cat people may hand out 1 sip to 1 dog person",
    "Armwrestling between ${player1} and ${player2}, the loser must drink 2 sips for weakness",
    "Rhymes, come up with a rhyme word. The first one who doesn't rhyme or doesn't come up with anything drinks 3 sips. ${player1} starts.",
    "${player1}, play fuck, marry, kill. If you don't want to do it drink 2 sips",
    "${player1} must drink one sip without hands, if you mess up you must drink 5 sips",
    "If you have your legs crossed you must drink 2 sips",
    "Take turns saying a word to form a sentence together. The person who messes up must drink 3 sips",
    "${player1}, what is your favorite fruit? That's your nickname until the end of the game",
    "${player1}, what is Obama's last name? Get it wrong, you have to drink 3 sips. Shame on you",
    "If you took less than 2,000 steps today you have to drink 2 sips, you lazy sack",
    "Who is your favorite person present? Give this person a hug and drink 3 sips together",
    "${player1}, shake everyone's hands. For every person you don't shake hands you drink 1 sip",
    "If you smoke cigarettes you must drink 3 sips",
    "If you vape you may give away 3 sips",
    "If you drink 43 you may give someone 4 sips and another 3 sips",
    "Passoa or similar beverage drinkers must drink 3 sips",
    "${player1}, what is your favorite color? Your nickname is then your favorite color",
    "Is ${player1} bigger than ${player2}? Then they need to drink 3 sips",
    "Pasta or fries? The majority drinks 2 sips",
    "${player1} say your best pickup line to ${player2}. The group decides if you can hand out 3 sips or not",
    "If you've been working out this week you have to drink 2 sips. You are doing too well so just compensate",
    "If you've ever filled shelves in a shop you have to drink 3 sips",
    "If you're a vegetarian you can give away 5 sips, go you",
    "The first person to see something brown gets to drink 3 sips",
    "The last person to put 2 hands in the air must drink 3 sips",
    "People without a driver's license drink 2 sips",
    "The least drunk person drinks 3 sips",
    "${player1}, do 5 squats with a sip between each squat",
    "The next person to look at the phone (except the gamemaster) must drink 5 sips",
    "The person who has ever peed on someone else may give away 5 sips",
    "${player1}, swap the drinks of 2 players of your choice",
    "${player1}, name 3 songs by Avril Lavigne or drink 3 sips",
    "${player1}, lick the forearm of ${player2} or drink 3 sips",
    "${player1} and ${player2}, change shoes or drink 5 sips",
    "Have you been or have you ever dumped someone on your phone? Then hand out 3 sips",
    "${player1}, reenact a movie scene without making a sound. You and the person who guesses may hand out 3 sips. Otherwise, drink 3 sips yourself",
    "The person who had sex last gets to pass out 3 sips",
    "If you like an emo girl you must drink 3 sips",
    "${player1} if you can do a handstand, show it. Otherwise take 3 sips",
    "At the same time, choose between steak and fries or butter cake. Everyone who chose the answer with the most votes may take 3 sips",
    "Evening people may hand out 5 sips",
    "${player1} whisper a sentence into the ear of the person to your right. If the sentence is still correct at the end of the round, no one has to drink", 
    "Swifties, you may hand out 3 sips",
    "Ring wearers may pass out 3 sips",
    "Go one round on the bus ${player1}",
    "Name the title of the song that is on now. If there is no music or you guess wrong you must drink 3 sips",
    "If you drank alcohol before it was legal for you you must drink 3 sips. Bad of you",
    "If you had a cup of coffee today you must drink 3 sips",
    "${player1} finish the text: '130 on the' or drink 3 sips",
    "If you drink from a glass you may give away 3 sips. Environmentalist",
    "The number of goals Ajax last scored ${player1} must drink",
    "People with gluten intolerance are allowed to give out 3 sips",
    "${player1} go to https://moetikeenriet.at/ and do what it says",
    "Do a game of fingering (put your finger on the glass and guess the number of fingers that stay on the glass)",
    "${player1}, name the colors of the rainbow in the correct order or drink as many as colors you get wrong",
    "${player1} and ${player2}, take a sip of each other's drink or drink 2 of your own",
    "The person with the next birthday gets to hand out 3 sips",
    "If you are reading this you must drink 3 sips",
    "${player1}, what does an STD mean? If you're wrong you drink 3 sips",
    "If you support Feyenoord you have to drink 5 sips, ieuw",
]