let sexytimeoriginal = [
    "Go to moetikeenriet.at",
    "Trek een bak",
    "The last person that barfed drinks 5 sips",
    "Drink 5 sips if you have smaller biceps than Cas",
    "Give out 3 sips if you have an attention deficiency",
    "Drink 5 sips if you have beer, drink 3 if you have wine, shot if something else",
    "Drink 3 sips if you are getting a beer belly",
    "Give out 3 sips if you have a girlfriend",
    "Truth or dare for 5 sips",
    "Drink 3 sips if you ever lost your bicycle",
    "Asians give out 5 sips",
    "Choose someone, they have to drink the same amount as you do for this prompt",
    "${player1}, give ${player2} a top up on their drink",
    "If ${player1} is the weakest player, trek een bak",
    "If Jelte is there, hum a song and give away 10 sips if he guesses it correctly",
    "Do a game of fingering",
    "Do a game of 'vijven' for an anytimer",
    "If Maiko is drinking 43, ${player1} can give away 10 sips",
    "If Cas went to the gym today, ${player1} can give away 10 sips",
    "If Willem played DDrace in the last week, ${player1} can give away 5 sips",
    "If Jort corrected someone today, ${player1} can give away 10 sips",
    "If Mathew watched twitch today, ${player1} can give away 10 sips",
    "If Jelte went on a walk today, ${player1} can give away 10 sips",
    "${player1} can gets an anytimer on ${player2}",
    "The person who had sex last gets to pass out 3 sips",
    "If you ate meat today, you have to drink 3 sips you filthy animal",
    "DO A WATERFALL, finish with ${player1}",
    "${player1}, drink 5 sips, the person to your right 4, over there to the right 3, ...",
    "${player1}, show your last 3 pictures on your phone or drink 5 sips",
    "Decide together who is the smartest person, this one drinks 3 sips. Wise person",
    
]